package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.sapient.Users;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final JspFactory _jspxFactory = JspFactory.getDefaultFactory();

  private static java.util.List _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.AnnotationProcessor _jsp_annotationprocessor;

  public Object getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_annotationprocessor = (org.apache.AnnotationProcessor) getServletConfig().getServletContext().getAttribute(org.apache.AnnotationProcessor.class.getName());
  }

  public void _jspDestroy() {
  }

  public void _jspService(HttpServletRequest request, HttpServletResponse response)
        throws java.io.IOException, ServletException {

    PageContext pageContext = null;
    HttpSession session = null;
    ServletContext application = null;
    ServletConfig config = null;
    JspWriter out = null;
    Object page = this;
    JspWriter _jspx_out = null;
    PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\n");
      out.write("\n");
      out.write("\n");
      out.write("<html lang=\"en\">\n");
      out.write("  <head>\n");
      out.write("    <meta charset=\"utf-8\">\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n");
      out.write("    <title>Ustora Demo</title>\n");
      out.write("    \n");
      out.write("    <!-- Google Fonts -->\n");
      out.write("    <link href='http://fonts.googleapis.com/css?family=Titillium+Web:400,200,300,700,600' rel='stylesheet' type='text/css'>\n");
      out.write("    <link href='http://fonts.googleapis.com/css?family=Roboto+Condensed:400,700,300' rel='stylesheet' type='text/css'>\n");
      out.write("    <link href='http://fonts.googleapis.com/css?family=Raleway:400,100' rel='stylesheet' type='text/css'>\n");
      out.write("    \n");
      out.write("    <!-- Bootstrap -->\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/bootstrap.min.css\">\n");
      out.write("    \n");
      out.write("    <!-- Font Awesome -->\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/font-awesome.min.css\">\n");
      out.write("    \n");
      out.write("    <!-- Custom CSS -->\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/owl.carousel.css\">\n");
      out.write("    <link rel=\"stylesheet\" href=\"style.css\">\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/responsive.css\">\n");
      out.write("\n");
      out.write("    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->\n");
      out.write("    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->\n");
      out.write("    <!--[if lt IE 9]>\n");
      out.write("      <script src=\"https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js\"></script>\n");
      out.write("      <script src=\"https://oss.maxcdn.com/respond/1.4.2/respond.min.js\"></script>\n");
      out.write("    <![endif]-->\n");
      out.write("  </head>\n");
      out.write("  <body>\n");
      out.write("   \n");
      out.write("    <div class=\"header-area\">\n");
      out.write("        <div class=\"container\">\n");
      out.write("            <div class=\"row\">\n");
      out.write("                <div class=\"col-md-8\">\n");
      out.write("                    <div class=\"user-menu\">\n");
      out.write("                        <ul>\n");
      out.write("                            <li><a href=\"#\"><i class=\"fa fa-user\"></i> My Account</a></li>\n");
      out.write("                            <li><a href=\"#\"><i class=\"fa fa-heart\"></i> Wishlist</a></li>\n");
      out.write("                            <li><a href=\"cart.html\"><i class=\"fa fa-user\"></i> My Cart</a></li>\n");
      out.write("                            <li><a href=\"checkout.html\"><i class=\"fa fa-user\"></i> Checkout</a></li>\n");
      out.write("                            <li><a href=\"Login.html\"><i class=\"fa fa-user\"></i> Login</a></li>\n");
      out.write("                        </ul>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("                \n");
      out.write("                <div class=\"col-md-4\">\n");
      out.write("                    <div class=\"header-right\">\n");
      out.write("                        <ul class=\"list-unstyled list-inline\">\n");
      out.write("                            <li class=\"dropdown dropdown-small\">\n");
      out.write("                                <a data-toggle=\"dropdown\" data-hover=\"dropdown\" class=\"dropdown-toggle\" href=\"#\"><span class=\"key\">currency :</span><span class=\"value\">USD </span><b class=\"caret\"></b></a>\n");
      out.write("                                <ul class=\"dropdown-menu\">\n");
      out.write("                                    <li><a href=\"#\">USD</a></li>\n");
      out.write("                                    <li><a href=\"#\">INR</a></li>\n");
      out.write("                                    <li><a href=\"#\">GBP</a></li>\n");
      out.write("                                </ul>\n");
      out.write("                            </li>\n");
      out.write("\n");
      out.write("                            <li class=\"dropdown dropdown-small\">\n");
      out.write("                                <a data-toggle=\"dropdown\" data-hover=\"dropdown\" class=\"dropdown-toggle\" href=\"#\"><span class=\"key\">language :</span><span class=\"value\">English </span><b class=\"caret\"></b></a>\n");
      out.write("                                <ul class=\"dropdown-menu\">\n");
      out.write("                                    <li><a href=\"#\">English</a></li>\n");
      out.write("                                    <li><a href=\"#\">French</a></li>\n");
      out.write("                                    <li><a href=\"#\">German</a></li>\n");
      out.write("                                    <li>");
 Users user=(Users)request.getSession().getAttribute("NewUser"); 
      out.write("</li>\n");
      out.write("                                </ul>\n");
      out.write("                            </li>\n");
      out.write("                             ");
 out.println(user.getName()); 
      out.write("\n");
      out.write("                           \n");
      out.write("                        </ul>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </div> <!-- End header area -->\n");
      out.write("    \n");
      out.write("    <div class=\"site-branding-area\">\n");
      out.write("        <div class=\"container\">\n");
      out.write("            <div class=\"row\">\n");
      out.write("                <div class=\"col-sm-6\">\n");
      out.write("                    <div class=\"logo\">\n");
      out.write("                        <h1><a href=\"./\"><img src=\"img/logo.png\"></a></h1>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("                \n");
      out.write("                <div class=\"col-sm-6\">\n");
      out.write("                    <div class=\"shopping-item\">\n");
      out.write("                        <a href=\"cart.html\">Cart - <span class=\"cart-amunt\">$100</span> <i class=\"fa fa-shopping-cart\"></i> <span class=\"product-count\">5</span></a>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </div> <!-- End site branding area -->\n");
      out.write("    \n");
      out.write("    <div class=\"mainmenu-area\">\n");
      out.write("        <div class=\"container\">\n");
      out.write("            <div class=\"row\">\n");
      out.write("                <div class=\"navbar-header\">\n");
      out.write("                    <button type=\"button\" class=\"navbar-toggle\" data-toggle=\"collapse\" data-target=\".navbar-collapse\">\n");
      out.write("                        <span class=\"sr-only\">Toggle navigation</span>\n");
      out.write("                        <span class=\"icon-bar\"></span>\n");
      out.write("                        <span class=\"icon-bar\"></span>\n");
      out.write("                        <span class=\"icon-bar\"></span>\n");
      out.write("                    </button>\n");
      out.write("                </div> \n");
      out.write("                <div class=\"navbar-collapse collapse\">\n");
      out.write("                    <ul class=\"nav navbar-nav\">\n");
      out.write("                        <li class=\"active\"><a href=\"index.html\">Home</a></li>\n");
      out.write("                        <li><a href=\"shop.jsp\">Shop page</a></li>\n");
      out.write("                        <li><a href=\"single-product.jsp\">Single product</a></li>\n");
      out.write("                        <li><a href=\"cart.html\">Cart</a></li>\n");
      out.write("                        <li><a href=\"checkout.html\">Checkout</a></li>\n");
      out.write("                        <li><a href=\"#\">Category</a></li>\n");
      out.write("                        <li><a href=\"#\">Others</a></li>\n");
      out.write("                        <li><a href=\"#\">Contact</a></li>\n");
      out.write("                    </ul>\n");
      out.write("                </div>  \n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </div> <!-- End mainmenu area -->\n");
      out.write("    \n");
      out.write("    <div class=\"slider-area\">\n");
      out.write("        \t<!-- Slider -->\n");
      out.write("\t\t\t<div class=\"block-slider block-slider4\">\n");
      out.write("\t\t\t\t<ul class=\"\" id=\"bxslider-home4\">\n");
      out.write("\t\t\t\t\t<li>\n");
      out.write("\t\t\t\t\t\t<img src=\"img/h4-slide.png\" alt=\"Slide\">\n");
      out.write("\t\t\t\t\t\t<div class=\"caption-group\">\n");
      out.write("\t\t\t\t\t\t\t<h2 class=\"caption title\">\n");
      out.write("\t\t\t\t\t\t\t\tiPhone <span class=\"primary\">6 <strong>Plus</strong></span>\n");
      out.write("\t\t\t\t\t\t\t</h2>\n");
      out.write("\t\t\t\t\t\t\t<h4 class=\"caption subtitle\">Dual SIM</h4>\n");
      out.write("\t\t\t\t\t\t\t<a class=\"caption button-radius\" href=\"#\"><span class=\"icon\"></span>Shop now</a>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</li>\n");
      out.write("\t\t\t\t\t<li><img src=\"img/h4-slide2.png\" alt=\"Slide\">\n");
      out.write("\t\t\t\t\t\t<div class=\"caption-group\">\n");
      out.write("\t\t\t\t\t\t\t<h2 class=\"caption title\">\n");
      out.write("\t\t\t\t\t\t\t\tby one, get one <span class=\"primary\">50% <strong>off</strong></span>\n");
      out.write("\t\t\t\t\t\t\t</h2>\n");
      out.write("\t\t\t\t\t\t\t<h4 class=\"caption subtitle\">school supplies & backpacks.*</h4>\n");
      out.write("\t\t\t\t\t\t\t<a class=\"caption button-radius\" href=\"#\"><span class=\"icon\"></span>Shop now</a>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</li>\n");
      out.write("\t\t\t\t\t<li><img src=\"img/h4-slide3.png\" alt=\"Slide\">\n");
      out.write("\t\t\t\t\t\t<div class=\"caption-group\">\n");
      out.write("\t\t\t\t\t\t\t<h2 class=\"caption title\">\n");
      out.write("\t\t\t\t\t\t\t\tApple <span class=\"primary\">Store <strong>Ipod</strong></span>\n");
      out.write("\t\t\t\t\t\t\t</h2>\n");
      out.write("\t\t\t\t\t\t\t<h4 class=\"caption subtitle\">Select Item</h4>\n");
      out.write("\t\t\t\t\t\t\t<a class=\"caption button-radius\" href=\"#\"><span class=\"icon\"></span>Shop now</a>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</li>\n");
      out.write("\t\t\t\t\t<li><img src=\"img/h4-slide4.png\" alt=\"Slide\">\n");
      out.write("\t\t\t\t\t\t<div class=\"caption-group\">\n");
      out.write("\t\t\t\t\t\t  <h2 class=\"caption title\">\n");
      out.write("\t\t\t\t\t\t\t\tApple <span class=\"primary\">Store <strong>Ipod</strong></span>\n");
      out.write("\t\t\t\t\t\t\t</h2>\n");
      out.write("\t\t\t\t\t\t\t<h4 class=\"caption subtitle\">& Phone</h4>\n");
      out.write("\t\t\t\t\t\t\t<a class=\"caption button-radius\" href=\"#\"><span class=\"icon\"></span>Shop now</a>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</li>\n");
      out.write("\t\t\t\t</ul>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<!-- ./Slider -->\n");
      out.write("    </div> <!-- End slider area -->\n");
      out.write("    \n");
      out.write("    <div class=\"promo-area\">\n");
      out.write("        <div class=\"zigzag-bottom\"></div>\n");
      out.write("        <div class=\"container\">\n");
      out.write("            <div class=\"row\">\n");
      out.write("                <div class=\"col-md-3 col-sm-6\">\n");
      out.write("                    <div class=\"single-promo promo1\">\n");
      out.write("                        <i class=\"fa fa-refresh\"></i>\n");
      out.write("                        <p>30 Days return</p>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"col-md-3 col-sm-6\">\n");
      out.write("                    <div class=\"single-promo promo2\">\n");
      out.write("                        <i class=\"fa fa-truck\"></i>\n");
      out.write("                        <p>Free shipping</p>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"col-md-3 col-sm-6\">\n");
      out.write("                    <div class=\"single-promo promo3\">\n");
      out.write("                        <i class=\"fa fa-lock\"></i>\n");
      out.write("                        <p>Secure payments</p>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"col-md-3 col-sm-6\">\n");
      out.write("                    <div class=\"single-promo promo4\">\n");
      out.write("                        <i class=\"fa fa-gift\"></i>\n");
      out.write("                        <p>New products</p>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </div> <!-- End promo area -->\n");
      out.write("    \n");
      out.write("    <div class=\"maincontent-area\">\n");
      out.write("        <div class=\"zigzag-bottom\"></div>\n");
      out.write("        <div class=\"container\">\n");
      out.write("            <div class=\"row\">\n");
      out.write("            <!-- ---------------------------------PRODUCTS---------------------------------------- -->\n");
      out.write("                <div class=\"col-md-12\">\n");
      out.write("                    <div class=\"latest-product\">\n");
      out.write("                        <h2 class=\"section-title\">Latest Products</h2>\n");
      out.write("                        <div class=\"product-carousel\">\n");
      out.write("                            <div class=\"single-product\">\n");
      out.write("                                <div class=\"product-f-image\">\n");
      out.write("                                    <img src=\"img/product-1.jpg\" alt=\"\">\n");
      out.write("                                    <div class=\"product-hover\">\n");
      out.write("                                        <a href=\"#\" class=\"add-to-cart-link\"><i class=\"fa fa-shopping-cart\"></i> Add to cart</a>\n");
      out.write("                                        <a href=\"single-product.html\" class=\"view-details-link\"><i class=\"fa fa-link\"></i> See details</a>\n");
      out.write("                                    </div>\n");
      out.write("                                </div>\n");
      out.write("                                \n");
      out.write("                                <h2><a href=\"single-product.html\">Samsung Galaxy s5- 2015</a></h2>\n");
      out.write("                                \n");
      out.write("                                <div class=\"product-carousel-price\">\n");
      out.write("                                    <ins>$700.00</ins> <del>$100.00</del>\n");
      out.write("                                </div> \n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("    <!-- ----------------------------------------------------------------------------------------- -->\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </div> <!-- End main content area -->\n");
      out.write("    \n");
      out.write("    <div class=\"brands-area\">\n");
      out.write("        <div class=\"zigzag-bottom\"></div>\n");
      out.write("        <div class=\"container\">\n");
      out.write("        <!-- ------------------------------BRANDS AREA------------------------------------------------ -->\n");
      out.write("            <div class=\"row\">\n");
      out.write("                <div class=\"col-md-12\">\n");
      out.write("                    <div class=\"brand-wrapper\">\n");
      out.write("                        <div class=\"brand-list\">\n");
      out.write("                            <img src=\"img/brand1.png\" alt=\"\">\n");
      out.write("                            <img src=\"img/brand2.png\" alt=\"\">\n");
      out.write("                            <img src=\"img/brand3.png\" alt=\"\">\n");
      out.write("                            <img src=\"img/brand4.png\" alt=\"\">\n");
      out.write("                            <img src=\"img/brand5.png\" alt=\"\">\n");
      out.write("                            <img src=\"img/brand6.png\" alt=\"\">\n");
      out.write("                            <img src=\"img/brand1.png\" alt=\"\">\n");
      out.write("                            <img src=\"img/brand2.png\" alt=\"\">                            \n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("            <!-- --------------------------------------------------------------------------------------- -->\n");
      out.write("        </div>\n");
      out.write("    </div> <!-- End brands area -->\n");
      out.write("    \n");
      out.write("    <div class=\"product-widget-area\">\n");
      out.write("        <div class=\"zigzag-bottom\"></div>\n");
      out.write("        <div class=\"container\">\n");
      out.write("            <div class=\"row\">\n");
      out.write("            <!-- ----------------------------------------- TOP SELLERS------------------------------------------------------ -->\n");
      out.write("                <div class=\"col-md-4\">\n");
      out.write("                    <div class=\"single-product-widget\">\n");
      out.write("                        <h2 class=\"product-wid-title\">Top Sellers</h2>\n");
      out.write("                        <a href=\"\" class=\"wid-view-more\">View All</a>\n");
      out.write("                        <!-- ---------------TOP SELLERS PRODUCT LIST STARTS HERE-----------  -->\n");
      out.write("                        <div class=\"single-wid-product\">\n");
      out.write("                            <a href=\"single-product.html\"><img src=\"img/product-thumb-1.jpg\" alt=\"\" class=\"product-thumb\"></a>\n");
      out.write("                            <h2><a href=\"single-product.html\">Sony Smart TV - 2015</a></h2>\n");
      out.write("                            <div class=\"product-wid-rating\">\n");
      out.write("                                <i class=\"fa fa-star\"></i>\n");
      out.write("                                <i class=\"fa fa-star\"></i>\n");
      out.write("                                <i class=\"fa fa-star\"></i>\n");
      out.write("                                <i class=\"fa fa-star\"></i>\n");
      out.write("                                <i class=\"fa fa-star\"></i>\n");
      out.write("                            </div>\n");
      out.write("                            <div class=\"product-wid-price\">\n");
      out.write("                                <ins>$400.00</ins> <del>$425.00</del>\n");
      out.write("                            </div>                            \n");
      out.write("                        </div>\n");
      out.write("                         <!-- ---------------TOP SELLERS PRODUCT LIST ENDS HERE-----------  -->\n");
      out.write("                       \n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("                <!-- -----------------------TOP SELLERS ENDS HERE ------------------------->\n");
      out.write("                <div class=\"col-md-4\">\n");
      out.write("                    <div class=\"single-product-widget\">\n");
      out.write("                        <h2 class=\"product-wid-title\">Recently Viewed</h2>\n");
      out.write("                        <a href=\"#\" class=\"wid-view-more\">View All</a>\n");
      out.write("                         <!-- ---------------RECENTLY VIEWED PRODUCT STARTS HERE-----------  -->\n");
      out.write("                        <div class=\"single-wid-product\">\n");
      out.write("                            <a href=\"single-product.html\"><img src=\"img/product-thumb-4.jpg\" alt=\"\" class=\"product-thumb\"></a>\n");
      out.write("                            <h2><a href=\"single-product.html\">Sony playstation microsoft</a></h2>\n");
      out.write("                            <div class=\"product-wid-rating\">\n");
      out.write("                                <i class=\"fa fa-star\"></i>\n");
      out.write("                                <i class=\"fa fa-star\"></i>\n");
      out.write("                                <i class=\"fa fa-star\"></i>\n");
      out.write("                                <i class=\"fa fa-star\"></i>\n");
      out.write("                                <i class=\"fa fa-star\"></i>\n");
      out.write("                            </div>\n");
      out.write("                            <div class=\"product-wid-price\">\n");
      out.write("                                <ins>$400.00</ins> <del>$425.00</del>\n");
      out.write("                            </div>                            \n");
      out.write("                        </div>\n");
      out.write("                        \n");
      out.write("                        \n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("                 <!-- ---------------RECENTLY VIEWED PRODUCT ENDS HERE-----------  -->\n");
      out.write("                <div class=\"col-md-4\">\n");
      out.write("                    <div class=\"single-product-widget\">\n");
      out.write("                        <h2 class=\"product-wid-title\">Top New</h2>\n");
      out.write("                        <a href=\"#\" class=\"wid-view-more\">View All</a>\n");
      out.write("                         <!-- ---------------TOP NEW  STARTS HERE-----------  -->\n");
      out.write("                        <div class=\"single-wid-product\">\n");
      out.write("                            <a href=\"single-product.html\"><img src=\"img/product-thumb-3.jpg\" alt=\"\" class=\"product-thumb\"></a>\n");
      out.write("                            <h2><a href=\"single-product.html\">Apple new i phone 6</a></h2>\n");
      out.write("                            <div class=\"product-wid-rating\">\n");
      out.write("                                <i class=\"fa fa-star\"></i>\n");
      out.write("                                <i class=\"fa fa-star\"></i>\n");
      out.write("                                <i class=\"fa fa-star\"></i>\n");
      out.write("                                <i class=\"fa fa-star\"></i>\n");
      out.write("                                <i class=\"fa fa-star\"></i>\n");
      out.write("                            </div>\n");
      out.write("                            <div class=\"product-wid-price\">\n");
      out.write("                                <ins>$400.00</ins> <del>$425.00</del>\n");
      out.write("                            </div>                            \n");
      out.write("                        </div>\n");
      out.write("                        \n");
      out.write("                       \n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("                 <!-- ---------------TOP NEW ENDS HERE-----------  -->\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </div> <!-- End product widget area -->\n");
      out.write("    \n");
      out.write("    <div class=\"footer-top-area\">\n");
      out.write("        <div class=\"zigzag-bottom\"></div>\n");
      out.write("        <div class=\"container\">\n");
      out.write("            <div class=\"row\">\n");
      out.write("                <div class=\"col-md-3 col-sm-6\">\n");
      out.write("                    <div class=\"footer-about-us\">\n");
      out.write("                        <h2>u<span>Stora</span></h2>\n");
      out.write("                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Perferendis sunt id doloribus vero quam laborum quas alias dolores blanditiis iusto consequatur, modi aliquid eveniet eligendi iure eaque ipsam iste, pariatur omnis sint! Suscipit, debitis, quisquam. Laborum commodi veritatis magni at?</p>\n");
      out.write("                        <div class=\"footer-social\">\n");
      out.write("                            <a href=\"#\" target=\"_blank\"><i class=\"fa fa-facebook\"></i></a>\n");
      out.write("                            <a href=\"#\" target=\"_blank\"><i class=\"fa fa-twitter\"></i></a>\n");
      out.write("                            <a href=\"#\" target=\"_blank\"><i class=\"fa fa-youtube\"></i></a>\n");
      out.write("                            <a href=\"#\" target=\"_blank\"><i class=\"fa fa-linkedin\"></i></a>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("                \n");
      out.write("                <div class=\"col-md-3 col-sm-6\">\n");
      out.write("                    <div class=\"footer-menu\">\n");
      out.write("                        <h2 class=\"footer-wid-title\">User Navigation </h2>\n");
      out.write("                        <ul>\n");
      out.write("                            <li><a href=\"#\">My account</a></li>\n");
      out.write("                            <li><a href=\"#\">Order history</a></li>\n");
      out.write("                            <li><a href=\"#\">Wishlist</a></li>\n");
      out.write("                            <li><a href=\"#\">Vendor contact</a></li>\n");
      out.write("                            <li><a href=\"#\">Front page</a></li>\n");
      out.write("                        </ul>                        \n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("                \n");
      out.write("                <div class=\"col-md-3 col-sm-6\">\n");
      out.write("                    <div class=\"footer-menu\">\n");
      out.write("                        <h2 class=\"footer-wid-title\">Categories</h2>\n");
      out.write("                        <ul>\n");
      out.write("                            <li><a href=\"#\">Mobile Phone</a></li>\n");
      out.write("                            <li><a href=\"#\">Home accesseries</a></li>\n");
      out.write("                            <li><a href=\"#\">LED TV</a></li>\n");
      out.write("                            <li><a href=\"#\">Computer</a></li>\n");
      out.write("                            <li><a href=\"#\">Gadets</a></li>\n");
      out.write("                        </ul>                        \n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("                \n");
      out.write("                <div class=\"col-md-3 col-sm-6\">\n");
      out.write("                    <div class=\"footer-newsletter\">\n");
      out.write("                        <h2 class=\"footer-wid-title\">Newsletter</h2>\n");
      out.write("                        <p>Sign up to our newsletter and get exclusive deals you wont find anywhere else straight to your inbox!</p>\n");
      out.write("                        <div class=\"newsletter-form\">\n");
      out.write("                            <form action=\"#\">\n");
      out.write("                                <input type=\"email\" placeholder=\"Type your email\">\n");
      out.write("                                <input type=\"submit\" value=\"Subscribe\">\n");
      out.write("                            </form>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </div> <!-- End footer top area -->\n");
      out.write("    \n");
      out.write("    <div class=\"footer-bottom-area\">\n");
      out.write("        <div class=\"container\">\n");
      out.write("            <div class=\"row\">\n");
      out.write("                <div class=\"col-md-8\">\n");
      out.write("                    <div class=\"copyright\">\n");
      out.write("                        <p>&copy; 2015 uCommerce. All Rights Reserved. <a href=\"http://www.freshdesignweb.com\" target=\"_blank\">freshDesignweb.com</a></p>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("                \n");
      out.write("                <div class=\"col-md-4\">\n");
      out.write("                    <div class=\"footer-card-icon\">\n");
      out.write("                        <i class=\"fa fa-cc-discover\"></i>\n");
      out.write("                        <i class=\"fa fa-cc-mastercard\"></i>\n");
      out.write("                        <i class=\"fa fa-cc-paypal\"></i>\n");
      out.write("                        <i class=\"fa fa-cc-visa\"></i>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </div> <!-- End footer bottom area -->\n");
      out.write("   \n");
      out.write("    <!-- Latest jQuery form server -->\n");
      out.write("    <script src=\"https://code.jquery.com/jquery.min.js\"></script>\n");
      out.write("    \n");
      out.write("    <!-- Bootstrap JS form CDN -->\n");
      out.write("    <script src=\"http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js\"></script>\n");
      out.write("    \n");
      out.write("    <!-- jQuery sticky menu -->\n");
      out.write("    <script src=\"js/owl.carousel.min.js\"></script>\n");
      out.write("    <script src=\"js/jquery.sticky.js\"></script>\n");
      out.write("    \n");
      out.write("    <!-- jQuery easing -->\n");
      out.write("    <script src=\"js/jquery.easing.1.3.min.js\"></script>\n");
      out.write("    \n");
      out.write("    <!-- Main Script -->\n");
      out.write("    <script src=\"js/main.js\"></script>\n");
      out.write("    \n");
      out.write("    <!-- Slider -->\n");
      out.write("    <script type=\"text/javascript\" src=\"js/bxslider.min.js\"></script>\n");
      out.write("\t<script type=\"text/javascript\" src=\"js/script.slider.js\"></script>\n");
      out.write("  </body>\n");
      out.write("</html>");
    } catch (Throwable t) {
      if (!(t instanceof SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else log(t.getMessage(), t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
